projects:
  soundscape:
    schemaPath: Users/milanravenell/Projects/soundscape/graphql/schema.json
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: API.ts
        docsFilePath: graphql
        maxDepth: 4
extensions:
  amplify:
    version: 3
