const initialState = {
  editSoundscapeNameDialogOpen: false,
  spotifyAccessToken: null,
  searchedTracks: [],
  selectedTracks: [],
  generatedTracks: [],
  curPlayingTrack: null,
  homeOptionsModalOpen: false,
  inviteError: false,
  inviteLinkDialogOpen: false,
  inviteSoundscape: null,
  inviteSuccess: false,
  inviteUser: null,
  isPaused: true,
  newSoundscapeLoading: false,
  playerToggle: false,
  accessTokenValid: null,
  activated: false,
  screen: 'player',
  soundscapeOptionsModalOpen: false,
  seedSongsModalOpen: false,
  addSeedSongsModalOpen: false,
  membersModalOpen: false,
  selectedSoundscapeIndex: null,
  soundscapes: null,
  loginDialogOpen: false,
  user: null,
  searchQuery: '',
  storedSpotifyId: null,
};

export default initialState;
